config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :entries do
      put :addpoint
    end
  resources :keywords, except: [:destroy]
  

  root 'entries#index'

  get '/feed', :to => 'entries#feed'
  get '/login', :to => 'sessions#new'

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get 'logout', to: 'sessions#destroy'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user
	belongs_to :keyword
	accepts_nested_attributes_for :keyword
	def self.today
		where("created_at >=?", Time.zone.now.beginning_of_day)
	end
	
	def self.search(search)
		where("content LIKE ?", "%#{search}%") || 
        where("name LIKE ?", "%#{search}%") ||
        where("entry.user.username LIKE ?", "%#{search}%")
    end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
	has_many :entries
	validates :name, presence: true, length: {minimum: 3, maximum: 25 }
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :entries
	has_secure_password

	before_save { self.email = email.downcase }
	
	validates :username, presence: true, uniqueness: { case_sensitive: false}, length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX}		
	validates :country, presence: true
	validates :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? 

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  


  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action."
  		redirect_to_root_path
  	end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
    if params[:search]
      @entries = Entry.search(params[:search]).order("created_at DESC")
    else
      
    end
  end

  def feed
    @entries = Entry.today.order('points DESC')
  end 
  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
    @entry.keyword = Keyword.new
  end

  # GET /entries/1/edit
  def edit
  end


  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user
      if @entry.save
        redirect_to @entry, :notice => "Thank you for sharing with us!"
        
      else
        format.html { render :new }
      end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def keyword
    @keyword
  end 

  def keyword_attributes=(attributes)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :username, :country, :city, :content, :points, :keyword_attributes => [:name])
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

	def index
		@keyword = Keyword.all
	end

	def new 
 		@keyword = Keyword.new
	end 

	def create
		@keyword = Keyword.new(keyword_params)

		if @keyword.save
			flash[:notice] = "Category was created successfully."
			redirect_to keyword_path
		else
			render 'new'
		end 
	end
	def show 
		
	end 

	private
	def keyword_params
		params.require(:keyword).permit(:name)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])

		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id 
			flash[:success] = "You have sucessfully logged in."
			redirect_to '/feed', :notice => "Welcome back!"
		else
			flash.now[:danger] = "There was something wrong with your login info."

			render 'new'
		end 
	end

	def destroy 
		session[:user_id] = nil
		redirect_to root_path, :notice => "Till next time."
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :logged_in_user, only: [:edit, :update]
  
  # GET /users
  # GET /users.json
  def index
    
    @users = User.all
  end 

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    
      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to the alpha blog #{@user.username}"
        redirect_to user_path(@user)
      else
        render 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to root_path, :notice => "You've updated your information!"
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      redirect_to users_url, :notice => "Thank you for sharing with us!"
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        
        redirect_to login_url, :notice => "You must login to do this."
      end 
    end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :country, :city, :points, :languages)
    end

    def require_admin
      if logged_in? && !current_user.admin?
        redirect_to root_path, :notice => "You aren't an admin, bub."
      end 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_entry.html.erb
<% previous_date = "" %>
<% obj.each do |entry| %>

<% current_date = "" %> 
<% current_date = (entry.created_at.strftime"%B %e %Y ")%>
<% if !(current_date == previous_date) %> 
<%= (entry.created_at.strftime"%B %e, %Y ")%>
<% end %> 
<% previous_date = (entry.created_at.strftime"%B %e %Y ")%>
            
        <div class="media" style="box-shadow: 0 0 8px rgba(0, 0, 0, 0.25);">
              <h4 class="media-heading" >
                <span style="font-size:20px">
                <%= link_to entry.name, entry_path(entry), :class => "media-title" %>
                </span>
                <span class="pull-right"><i class="fa fa-pencil" aria-hidden="true"></i>
                <i class="fa fa-cog" aria-hidden="true"></i>
                <i class="fa fa-trash-o" aria-hidden="true"></i></span>
              </h4>
          <div class="media-body">
          <div class="row">
            <div class="col-md-9">
              <div class="media-content">
                <%= entry.content %>
              </div>

            </div>

            <div class="col-md-3">
              <div class="media-info">
                      <span class= "pull-right" style="font-size:12px; color: blue">
                      <% if defined? entry.user.username? %>
                      <%= link_to entry.user.username, user_path(entry.user) %>
                      <% else %>
                      <p>Anonymous</p>
                      <% end %>
                      </span> <br>
                  
                       

                  <span class= "pull-right" style="font-size:10px">
                  <% if defined? entry.country? %>
                    <p> <%= entry.country %>, <%= entry.city %></p>

                  <% elsif defined? entry.user.country %> 
                   <p> <%= entry.user.country %>, <%= entry.user.city %></p></span> 
                  <% else %> 
                  <p>Unknown</p>
                 <% end %>
                   <br>
                       
                       
                  <a href="#" class="pull-right" style="font-size:20px;">  
                  <div class="two" style="text-align:center">
                    <b><%= entry.points %></b>
                  </div>
                  </a>
             </div>   
            </div>
            


            </div>
            <div class="row">
            <div class="col-md-12">
              <div class="media-info">
                    

                    <span class="pull-right">
                      Posted: <%= time_ago_in_words(entry.created_at) %> ago
                    </span><br>
                    <span class="pull-right"> <%= link_to 'Show', entry %> </span>
              </div>  
           <% if logged_in? && (current_user == entry.user || current_user.admin?) %> 
              <%= link_to 'Edit', entry %>
            <% end %>
            </div>
            </div>
          </div>
        </div>

            
          
         <% end %>

app/views/entries/_form.html.erb
<div class="test">
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <%= f.fields_for :keyword, @entry.keyword do |u| %>
<span class="input input--minoru h2">
   <%= u.text_field :name, :class => "input__field input__field--minoru"%>
    <label for="keyword_name" class="input__label input__label--minoru">
        <span class="input__label-content input__label-content--minoru">Keyword</span>
        </label>
  </span>
 <% end %>


    <span class="input input--minoru h2">
      <%= f.text_field :name,  :class => "input__field input__field--minoru" %>
      <label for="entry_name" class="input__label input__label--minoru">
        <span class="input__label-content input__label-content--minoru">Title</span>
        </label>
    </span>
    
    <div class="input-group" style="margin-left:30px;margin-bottom:20px;">
    			<div id="radioBtn" class="btn-group">
    					<a class="btn btn-primary btn-sm active" data-toggle="fun" data-title="Y">Public</a>
                        <a class="btn btn-primary btn-sm notActive" data-toggle="fun" data-title="X">Anonymous</a>
    					<a class="btn btn-primary btn-sm notActive" data-toggle="fun" data-title="N">Private</a>
          </div>
    	<input type="hidden" name="fun" id="fun">
    </div>
    
    <span class="input input--minoru h2" style="margin-left:30px;font-size:80%;width:150px">
        <%= f.text_field :city,  :class => "input__field input__field--minoru", :value => request.location.city %>
        <label for="entry_name" class="input__label input__label--minoru">
          <span class="input__label-content input__label-content--minoru">City</span>
          </label>
      </span>
      
      <span class="input input--minoru h2" style="font-size:80%;width:150px">
        <%= f.text_field :country,  :class => "input__field input__field--minoru", :value => request.location.country %>
        <label for="entry_name" class="input__label input__label--minoru">
          <span class="input__label-content input__label-content--minoru">Country</span>
          </label>
      </span>
    



  <div class="field" style="margin-left:30px;margin-right:30px">
    <%= f.text_area :content, placeholder: "Content" %>
  </div>
  
  <div class="actions variation-a">
    <%= f.submit 'submit', :class => "submitButton" %>
  </div>
<% end %>
</div>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/feed.html.erb
<div class="container-fluid" style="margin-top:50px;">
     
<h1>
  Popular Journal Entries for
  <%= Time.now.strftime("%m/%d/%Y")%> | <%= link_to 'New', new_entry_url %>

</h1>


<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Entryname</th>
      <th>Country</th>
      <th>City</th>
      <th>Content</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
            <% @entries.each do |entry| %>
            <div class="media" style="    box-shadow: 0 0 8px rgba(0, 0, 0, 0.25);">
              <span style="media-heading">
              <h3 class="media-title" > 
                <%= link_to entry.name, entry %></h3>
              </span>
              
          <div class="media-body">
          <div class="row">
            <div class="col-md-9">
              <div class="media-content">
               <i><%= entry.content %></i> 
              </div>
            </div>
            <div class="col-md-3">
              <div class="media-info">
                      <span class= "pull-right" style="font-size:12px; color: blue">
                      <% if defined? entry.user.username? %>
                      <%= link_to entry.user.username, user_path(entry.user) %>
                      <% else %>
                      <p>Anonymous</p>
                      <% end %>
                      </span> <br>
                  <span class= "pull-right" style="font-size:10px">
                  <% if entry.country? %>
                    <%= entry.country %>, <%= entry.city %>
                  <% elsif !entry.user.nil? && entry.user.country? %> 
                   <%= entry.user.country %>, <%= entry.user.city %>
                  <% else %> 
                  Unknown
                 <% end %>
                 </span>
                   <br>
                       
                       
                  <a href="#" class="pull-right" style="font-size:20px;">  
                  <div class="two" style="text-align:center">
                    <b><%= entry.points %></b>
                  </div>
                  </a>
             </div>   
            </div>
            


            </div>
            <div class="row">
            <div class="col-md-12">
              <div class="media-info">
                    

                    <span class="pull-right">
                      Posted: <%= time_ago_in_words(entry.created_at) %> ago
                    </span><br>
                    <span class="pull-right"> <%= link_to 'Show', entry %> </span>
              </div>  
             <% if logged_in? && (current_user == entry.user || current_user.admin?) %> 
              <%= link_to 'Edit', edit_entry_path(entry) %> |
            <% end %>
            </div>
            </div>

          
          
         
            

                 
          </div>
        </div>
         <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

    </div>

app/views/entries/index.html.erb
<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Country</th>
      <th>City</th>
      <th>Content</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
          <% if defined? entry.user.username? %>
                      <td><%= entry.user.username? %></td>
                      <% else %>
                      <td>Anonymous</td>
                      <% end %>
          <% if defined? entry.user.country? %>            
                  <td><%= entry.user.country %></td>
                  <td><%= entry.user.city %></td>
                  <% else %> 
                  <td> Unknown Location </td>
                  <% end %> 
        <td><%= entry.content %></td>
        <td><%= entry.points %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1> 
<%= link_to 'Back', feed_url %> | New Journal Entry
</h1>

<%= render 'form' %>

app/views/entries/show.html.erb
                   
                     
<p>
  <strong>Username:</strong>
   <% if defined? entry.user.username? %>
  <%= @entry.user.username%>
   <% else %>
   <p>Anonymous</p>
  <% end %>
</p>


                      
<% if @entry.country? %>
                    <%= @entry.country %>, <%= @entry.city %>
                  <% elsif !@entry.user.nil? && @entry.user.country? %> 
                   <%= @entry.user.country %>, <%= @entry.user.city %>
                  <% else %> 
                  Anonymous
                  <% end %>
<p>
  <strong>Title:</strong>
  <%= @entry.name%>
</p>




<p>
  <strong>Content:</strong>
  <%= @entry.content %>
</p>

<p>
  <strong>Points:</strong>
  <%= @entry.points %>
</p>

  <% if logged_in? && (current_user == @entry.user || current_user.admin?) %> 
              <%= link_to 'Edit', edit_entry_path(@entry) %> |
            <% end %>
<%= link_to 'Back', entries_path %>

app/views/keywords/index.html.erb
<h1>Listing Keywords</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @keyword.each do |keyword| %>
      <tr>
        <td><%= keyword.name %> </td> 
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/keywords/new.html.erb
<h1 align="center">Submit a keyword!</h1>



<%= form_for(@keyword, :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :name %>

</div>

<div class="col-sm-8">

<%= f.text_field :name, class: "form-control", placeholder: "Keyword", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit class: 'btn btn-primary btn-lg' %>

</div>

</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">

[ <%= link_to "Cancel request and return to articles listing", entries_path %> ]

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Universaljournal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Lato:100|Roboto:300,300i' %>
 
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
    <div id="page-content-wrapper" style="margin-left:0;">
    <div class="container">
    <h4 align="center" class="top-nav"><%= image_tag("ujSLEEK.png", :alt => "Join the Universe", height: '100', width: '400') %></h1>
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
                <li>
                    <a href="/feed/" class="[  animate  ]">
					    <span> HOME </span>
					    <span class="fa-lg pull-left"><i class="fa fa-globe"></i></span>
				    </a>
				</li>
				<li>
                    <a href="/feed/" class="[  animate  ]">
					    <span> FEED </span>
					    <span class="fa-lg pull-left"><i class="fa fa-globe"></i></span>
				    </a>
				</li>
				    <li>
				        <a href="/entries/new" class="animate">
					    <span class="desc animate"> WRITE </span>
					    <span class="fa-lg pull-left"><i class="fa fa-pencil-square"></i></span>
				        </a>
			        </li>
					<li>
					 <% if logged_in? %>

                        <%= link_to '<span class="desc animate">MY Journal</span><span class="fa-lg pull-left"><i class="fa fa-address-book"></i></span>'.html_safe, user_path(current_user), :class => "animate" %>  
                        
                        <% else %>
                        
                        <%= link_to '<span class="desc animate"> Login </span><span class="fa-lg pull-left"><i class="fa fa-address-book"></i></span>'.html_safe, login_path, :class => "animate" %>
                        
                        <% end %> 
                    </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <span class="input input--kyo">
		                    	<%= form_tag(entries_path, :method => "get", id: "search-form") do %>
		                       <%= text_field_tag :search, params[:search], placeholder: "Search Entries", :class => "input__field input__field--kyo" %>
		                       <% end %> 
		                       <% if !(:search.present?) %>
		                           <p>There are no entries containing the term(s) <%= params[:search] %> .</p>
		                       <% end %>
		                </span>
        <!-- Page Content -->
        
            <div class="container-fluid xyz">
                <div class="row">
                    <div class="col-lg-1">
                    </div>
                    <div class="col-lg-9">
                        <%= yield %>
                    </div>
                   <div class="col-md-2">
                       <% if logged_in? %>
                        Logged in as:
 
                       <b><%= current_user.username %></b>

                        <%= link_to 'Edit Profile', edit_user_path(current_user) %>  
                        <%= link_to 'Log_out', logout_path, method: :delete %>
                        
                        <% else %>
                        
                        <%= link_to 'Log_in', login_path %>
                        
                        <% end %> 
                   </div> 
                </div>
                
                <div class="row">
                   <%= debug(params) if Rails.env.development? %>
                </div> 
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>






  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  






</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <p> Username: <br> <%= f.text_field :username%>   </p>
    <p> Email: <br> <%= f.text_field :email%> </p>
    <p> Country: <br> <%= f.text_field :country%></p>
    <p> City: <br> <%= f.text_field :city%></p>
    <p> Password: <br> <%= f.password_field :password%></p>
    <p> Password Confirmation: <br> <%= f.password_field :password_confirmation%></p>
    <%= f.submit :Submit %> 

  
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Just <%= pluralize(@user.errors.count, "thing") %> before finishing edits!</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Country</th>
      <th>City</th>
      <th>Points</th>
      <th>Languages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.country %></td>
        <td><%= user.city %></td>
        <td><%= user.points %></td>
        <td><%= user.languages %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Universal Journal Signup</h1>

<div class="col-md-4">
	<h3>Features</h3>
	<p>You do not have to create an account on Universal Journal to post, but signing up for free gives you access to some great features.</p>
	<h3>Private Journal</h3>
	<p></p>
	<h2></h2>
	<p></p>

	You do not have to create an account on Universal Journal to be able to post. You can post anonymously when logged in or logged out. Upon submission of an anonymous journal entry, you will be given a link to 
</div>


	<%= render 'form' %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Just <%= pluralize(@user.errors.count, "thing") %> before signing up!</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username %>'s Journal!</h1>

<%= render 'entries/entry', obj: @user.entries %> 
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @user.languages %>
</p>

<%= link_to 'Back', users_path %>